#!/bin/bash

echo "Compiling..."
if g++ ./src/main.cpp -o dnd_generator $(pkg-config --cflags --libs gtk4 libadwaita-1); then
    echo "Compilation successful. Running..."
    ./dnd_generator > /dev/null # 2>&1
else
    echo "Compilation failed. The program will not be run." 
    exit 1
fi